server:
  port : 8081
spring:
  profiles:
    active: local
  application:
    name: "spring-boot-cassandra"
  data:
    cassandra:
      contact-points: 127.0.0.1
      port: 9042
      keyspace-name: spring_boot_cassandra_example